Update log.js to support async reporter plugins
unifiedjs/unified-engine pull request #71
Opened 2022-11-16 05:40 UTC by steveszc

Async reporters can be easily supported by `await`ing the reporter function.

### Initial checklist

*   [ ] I read the support docs 
*   [ ] I read the contributing guide 
*   [ ] I agree to follow the code of conduct 
*   [ ] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [ ] If applicable, I’ve added docs and tests

### Description of changes

Log.js can easily support sync reporter plugins by awaiting the reporter function. Currently the reporter function is called as a sync function.

Example: vfile-reporter-junit
https://github.com/kellyselden/vfile-reporter-junit/blob/master/index.js

2022-11-16 05:41 UTC, steveszc commented
Potentially related issue comment. Unclear if the decision to have reporter plugins be sync was an intentional design decision. https://github.com/unifiedjs/unified-engine/issues/62#issuecomment-1060396465

2022-11-16 11:31 UTC, remcohaszing requested changes
I see why this is useful. The types need to be updated though.

ESLint 8 also added support for async reporters.

2022-11-16 22:18 UTC, steveszc commented
I am getting type errors on `main` when I run `npm test`. 

Not sure I can get this PR passing until main is working...

2022-11-17 16:47 UTC, steveszc commented
@wooorm Test added and passing

2022-11-17 16:58 UTC, remcohaszing approved these changes

2022-11-19 20:08 UTC, wooorm approved these changes

2022-11-19 20:09 UTC, merged

2022-11-19 20:12 UTC, wooorm commented
Thanks, released in [10.1.0](https://github.com/unifiedjs/unified-engine/releases/tag/10.1.0)!